// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACuH8I5aSNthya47i0DnhiRUSiHlRnqb4',
    appId: '1:704332307655:web:a168aa12e810e0b7ce32e2',
    messagingSenderId: '704332307655',
    projectId: 'assengaprime-92489',
    authDomain: 'assengaprime-92489.firebaseapp.com',
    storageBucket: 'assengaprime-92489.appspot.com',
    measurementId: 'G-ELPZTLTQCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDX9Um-_pL1fQSrkRwASqXxKAugKfLmac',
    appId: '1:704332307655:android:1f9cf9c5b16b1d76ce32e2',
    messagingSenderId: '704332307655',
    projectId: 'assengaprime-92489',
    storageBucket: 'assengaprime-92489.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXL6gPazYa3vX1XaEZJMRk8rTUkCXs7PY',
    appId: '1:704332307655:ios:04cddb367c39376bce32e2',
    messagingSenderId: '704332307655',
    projectId: 'assengaprime-92489',
    storageBucket: 'assengaprime-92489.appspot.com',
    iosBundleId: 'com.example.assengadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXL6gPazYa3vX1XaEZJMRk8rTUkCXs7PY',
    appId: '1:704332307655:ios:a647fda56a6dc308ce32e2',
    messagingSenderId: '704332307655',
    projectId: 'assengaprime-92489',
    storageBucket: 'assengaprime-92489.appspot.com',
    iosBundleId: 'com.example.assengadmin.RunnerTests',
  );
}
